[features]
seeds = false
[programs.devnet]
vestor_using_anchor_chainlink_master = "4UdRaLosDf3eyifPjzZAbKfRzSasBFsvWHktYyeHpEPh"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/aadyakalra/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
